# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
brews:
  -
    name: goreleaser-playground
    tap:
      owner: dudash
      name: homebrew-tools
    folder: Formula
    homepage: "https://github.com/tektoncd/cli"
    description: Tekton CLI - The command line interface for interacting with Tekton
    test: |
      system "#{bin}/goreleaser-playground", "version"
    custom_block: |
      deprecate! date: "2022-04-26", because: :deprecated_upstream
      ohai "To upgrade your tekton cli, do the following:"
      ohai "  brew untap tektoncd/tools"
      ohai "  brew install tektoncd-cli"
      opoo "tapping is no longer needed, use the official homebrew formulae"
    install: |
      bin.install_symlink "tkn" => "kubectl-tkn"
      bin.install "tkn" => "tkn"
      output = Utils.popen_read("SHELL=bash #{bin}/tkn completion bash")
      (bash_completion/"tkn").write output
      output = Utils.popen_read("SHELL=zsh #{bin}/tkn completion zsh")
      (zsh_completion/"_tkn").write output
      prefix.install_metafiles
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
